### ISSUE TITLE
Can we enable different website versions based on the tags?

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/workshop-r-swe#2]
Hi @kkmann @cicdguy - quick question, since now we will have the second session of this workshop, slightly modified materials etc., I think it would be great if we could have different website versions accessible on https://openpharma.github.io/workshop-r-swe/. Similar as we have it e.g. in https://openpharma.github.io/mmrm. Would that be easily possible?

**Comment by kkmann** [comment]
I am not aware of how to do that - would just go with the respecitve latest.

**Comment by danielinteractive** [comment]
I wonder since in `pkgdown` that is possible it would be great if it could work here too :-) but yeah sure otherwise we just have the latest.

**Comment by cicdguy** [comment]
We don't have something like this for Quarto, just pkgdown at the moment.

**Comment by danielinteractive** [comment]
Alright thanks @cicdguy for the quick info! Let's hope they might add it at some point :-)
