### ISSUE TITLE
Update intro slides

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/workshop-r-swe#3]
- [x] Links
- [ ] People
	- [x] Daniel
	- [x] Liming - @clarkliming please add to the branch
	- [ ] Joe - @shajoezhu please add to the branch
	- [x] Shuang @shuangli22 please add to the branch
- [x] chat channel - waiting for @shajoezhu information
- [x] Slido - does not work in China, at least in the office I cannot even create an account on the website. What would be an alternative @shajoezhu @clarkliming @stevemun ?
	- [x] would https://www.mentimeter.com/ work?

**Comment by Stevemun** [comment]
Yes, menti works well. We have a shared menti account. I will give it to you tomorrow.

**Comment by danielinteractive** [comment]
Super thanks @Stevemun !
